version: '3.7'

services:
  nginx:
    restart: unless-stopped
    image: nginx:alpine
    container_name: nuxt_mdl_wine_nginx_dev
    ports:
      - "80:80"
      - "443:8443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/nginx_dev.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/ssl:/ssl_cert
      - ./storage/logs/nginx:/var/log/nginx
      - ./storage/static:/var/www/static
      - ./config/favicons:/var/www/static/favicons
      - ./storage/media:/var/www/media
    depends_on:
      - nuxt
      - django

  nuxt:
    image: nuxt_mdl_wine_nuxt:latest
    build:
      context: .
      dockerfile: ./config/dockerfiles/Nuxt.Dockerfile
      target: development-env
    container_name: nuxt_mdl_wine_nuxt_dev
    restart: unless-stopped
    expose:
      - "3000"
    working_dir: /app
    command:
      "npm run dev"

    volumes:
      - ./services/site:/app
      - /app/node_modules
      - ./storage/logs/nuxt:/root/.npm/_logs/

    environment:
      SERVER_DOMAIN_NAME: http://django:8000
      BROWSER_DOMAIN_NAME: https://localhost

    depends_on:
      - django

  django:
    restart: unless-stopped
    container_name: nuxt_mdl_wine_django_dev
    build:
      context: .
      dockerfile: ./config/dockerfiles/Django.Dockerfile
    working_dir: /app
    # command: bash -c "sleep 2 && python manage.py makemigrations"
    # command: bash -c "python manage.py migrate"

    command: bash -c "gunicorn -w 2 config.wsgi --reload -b 0.0.0.0:8000"
    volumes:
      - ./services/server:/app
      - ./config/fixtures:/fixtures
      - ./storage:/storage
      - ./storage/db:/storage/db
      - ./storage/logs/django:/var/log/django
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      CAPTCHA_SECRET: ${CAPTCHA_SECRET}
      EMAIL_HOST: ${EMAIL_HOST}
      SERVER_EMAIL: ${SERVER_EMAIL}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
    expose:
      - "8000"